language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

# command to install dependencies
install:
  - pip3 install .

# command to run tests
script:
  - python3 test.py
